---
title: Katy Presswood
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: base
email: asmith.esq@gmail.com
description: A website for the greatest and best art teacher in the world.
baseurl: 
sass:
  sass_dir: assets/stylesheets
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
